spring.application.name=marmoraria-orcamentos-api
server.port=8090
spring.datasource.url=jdbc:postgresql://localhost:5432/marmoraria_orcamentos
spring.datasource.username=postgres
spring.datasource.password=senha
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop